source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'bootstrap-sass', '~> 3.2', '>= 3.2.0.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'factory_girl_rails', '~> 4.8'
  gem 'faker', '~> 1.7', '>= 1.7.2'
  gem 'pry-rails', '~> 0.3.4'
  gem 'rspec-rails', '~> 3.5', '>= 3.5.2'
  gem 'simplecov', '~> 0.13.0', require: false
  gem 'database_cleaner', '~> 1.5', '>= 1.5.3'
  gem 'shoulda-matchers', '~> 3.1', '>= 3.1.1', require: false
end

group :development do
  # Capistrano to upload application
  gem 'capistrano', '~> 3.7', '>= 3.7.1'
  gem 'capistrano3-puma', '~> 1.2', '>= 1.2.1'
  gem 'capistrano-rails', '~> 1.2', '>= 1.2.2', require: false
  gem 'capistrano-bundler', '~> 1.2', require: false
  gem 'capistrano-rvm', '~> 0.1.2'
end
